Rekrut/Controllers/AuthController.cs
using System;
using System.Globalization;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using Rekrut.Models;
using MongoDB.Driver;
using MongoDB.Bson;

namespace Rekrut.Controllers
{
    [Authorize]
    public class AuthController : Controller
    {
        private ApplicationSignInManager _signInManager;
        private ApplicationUserManager _userManager;

        public AuthController()
        {
        }

        public AuthController(ApplicationUserManager userManager, ApplicationSignInManager signInManager )
        {
            UserManager = userManager;
            SignInManager = signInManager;
        }

        public ApplicationSignInManager SignInManager
        {
            get
            {
                return _signInManager ?? HttpContext.GetOwinContext().Get<ApplicationSignInManager>();
            }
            private set 
            { 
                _signInManager = value; 
            }
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        public async Task<JsonResult> UserInfo()
        {
            var db = new RekrutContext();
            var person = await db.People.Find(x => x.Username == User.Identity.Name).Project(x => new
            {
                employeeId = x.EmployeeId,
                username = x.Username,
                firstName = x.FirstName,
                lastName = x.LastName,
                jobTitle = x.JobTitle,
                img = x.Img == null ? "Content/images/default-" + (x.Gender == "M" ? "male" :"female") + ".png" : x.Img
            }).FirstOrDefaultAsync();
            return Json(new
            {
                person = person,
                projects = await db.Projects.CountAsync(y => y.Team.Members.Any(z => z.EmployeeId == person.employeeId)),
                tasks = await db.Tasks.CountAsync(y => y.AssignedTo == person.employeeId),
            }, JsonRequestBehavior.AllowGet);
        }
        
        //
        // GET: /Account/Login
        [AllowAnonymous]
        public ActionResult Login(string returnUrl)
        {
            ViewBag.ReturnUrl = returnUrl;
            return View();
        }

        //
        // POST: /Account/Login
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Login(LoginViewModel model, string returnUrl)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            // This doesn't count login failures towards account lockout
            // To enable password failures to trigger account lockout, change to shouldLockout: true
            var result = await SignInManager.PasswordSignInAsync(model.Email, model.Password, model.RememberMe, shouldLockout: false);
            switch (result)
            {
                case SignInStatus.Success:
                    return RedirectToLocal(returnUrl);
                case SignInStatus.LockedOut:
                    return View("Lockout");
                case SignInStatus.RequiresVerification:
                    return RedirectToAction("SendCode", new { ReturnUrl = returnUrl, RememberMe = model.RememberMe });
                case SignInStatus.Failure:
                default:
                    ModelState.AddModelError("", "Your Username and Password did not match. Please try again.");
                    return View(model);
            }
        }
        [AllowAnonymous]
        public async Task CreateAllUsers()
        {
            var db = new RekrutContext();
            var users = await db.People.Find(new BsonDocument()).Project(x => new { x.Email, x.Username }).ToListAsync();
            foreach (var one in users)
            {
                var user = new ApplicationUser { UserName = one.Username, Email = one.Email };
                var result = await UserManager.CreateAsync(user, "Password123.");
            }
        }
        //
        // POST: /Account/Register
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Register(RegisterViewModel model)
        {
            if (ModelState.IsValid)
            {
                var user = new ApplicationUser { UserName = model.Email, Email = model.Email };
                var result = await UserManager.CreateAsync(user, model.Password);
                if (result.Succeeded)
                {
                    await SignInManager.SignInAsync(user, isPersistent:false, rememberBrowser:false);
                    
                    // For more information on how to enable account confirmation and password reset please visit http://go.microsoft.com/fwlink/?LinkID=320771
                    // Send an email with this link
                    // string code = await UserManager.GenerateEmailConfirmationTokenAsync(user.Id);
                    // var callbackUrl = Url.Action("ConfirmEmail", "Account", new { userId = user.Id, code = code }, protocol: Request.Url.Scheme);
                    // await UserManager.SendEmailAsync(user.Id, "Confirm your account", "Please confirm your account by clicking <a href=\"" + callbackUrl + "\">here</a>");

                    return RedirectToAction("Index", "Home");
                }
                AddErrors(result);
            }

            // If we got this far, something failed, redisplay form
            return View(model);
        }

        //
        // GET: /Account/ForgotPassword
        [AllowAnonymous]
        public ActionResult ForgotPassword()
        {
            return View();
        }

        //
        // POST: /Account/ForgotPassword
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> ForgotPassword(ForgotPasswordViewModel model)
        {
            if (ModelState.IsValid)
            {
                var user = await UserManager.FindByNameAsync(model.Email);
                if (user == null || !(await UserManager.IsEmailConfirmedAsync(user.Id)))
                {
                    // Don't reveal that the user does not exist or is not confirmed
                    return View("ForgotPasswordConfirmation");
                }

                // For more information on how to enable account confirmation and password reset please visit http://go.microsoft.com/fwlink/?LinkID=320771
                // Send an email with this link
                // string code = await UserManager.GeneratePasswordResetTokenAsync(user.Id);
                // var callbackUrl = Url.Action("ResetPassword", "Account", new { userId = user.Id, code = code }, protocol: Request.Url.Scheme);		
                // await UserManager.SendEmailAsync(user.Id, "Reset Password", "Please reset your password by clicking <a href=\"" + callbackUrl + "\">here</a>");
                // return RedirectToAction("ForgotPasswordConfirmation", "Account");
            }

            // If we got this far, something failed, redisplay form
            return View(model);
        }

        //
        // GET: /Account/ResetPassword
        [AllowAnonymous]
        public ActionResult ResetPassword(string code)
        {
            return code == null ? View("Error") : View();
        }

        //
        // POST: /Account/ResetPassword
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> ResetPassword(ResetPasswordViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            var user = await UserManager.FindByNameAsync(model.Email);
            if (user == null)
            {
                // Don't reveal that the user does not exist
                return RedirectToAction("ResetPasswordConfirmation", "Account");
            }
            var result = await UserManager.ResetPasswordAsync(user.Id, model.Code, model.Password);
            if (result.Succeeded)
            {
                return RedirectToAction("ResetPasswordConfirmation", "Account");
            }
            AddErrors(result);
            return View();
        }

        //
        // POST: /Account/LogOff
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult LogOff()
        {
            AuthenticationManager.SignOut(DefaultAuthenticationTypes.ApplicationCookie);
            return RedirectToAction("login", "auth");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                if (_userManager != null)
                {
                    _userManager.Dispose();
                    _userManager = null;
                }

                if (_signInManager != null)
                {
                    _signInManager.Dispose();
                    _signInManager = null;
                }
            }

            base.Dispose(disposing);
        }

        #region Helpers
        // Used for XSRF protection when adding external logins
        private const string XsrfKey = "XsrfId";

        private IAuthenticationManager AuthenticationManager
        {
            get
            {
                return HttpContext.GetOwinContext().Authentication;
            }
        }

        private void AddErrors(IdentityResult result)
        {
            foreach (var error in result.Errors)
            {
                ModelState.AddModelError("", error);
            }
        }

        private ActionResult RedirectToLocal(string returnUrl)
        {

Rekrut/Views/Shared/Loading.cshtml
@{ 
    Layout = null;
}
<div class="load-bar" ng-if="loading">
    <div class="bar"></div>
    <div class="bar"></div>
    <div class="bar"></div>
</div>

Rekrut/Views/Shared/PersonCard.cshtml
@{
    Layout = null;
}
<div class="person-card">
    <div class="top">
        <button class="options"><i class="mdi mdi-dots-vertical"></i></button>
        <button class="close"><i class="mdi mdi-close"></i></button>
        <div class="img-holder">
            <img src="~/Content/images/guy-face.png" alt="User Face" />
        </div>
        <div class="info">
            <h1>{{peronCard.FirstName + " " + personCard.LastName}}: <b ng-bind="personCard.JobTitle"></b></h1>
            <h2 ng-bind="peronCard.Department"></h2>
            <div class="detail-group clearfix">
                <h3 class="pull-left"><b>Email:</b>{{personCard.Email}}</h3>
                <h3 class="pull-right"><b>Ext.:</b>{{personCard.Extension}}</h3>
            </div>
        </div>
        <div class="tabs-nav">
            <button class="active">Personals</button>
            <button>Skills</button>
            <button>Pros & Cons</button>
            <button>Interests</button>
            <button>Credentials</button>
        </div>
    </div>
    <div class="bottom">
        <div class="tab-content-inner">
            <div class="tab-content">
                <table>
                    <tr>
                        <td>
                            <label>Address</label>
                            <h1>{{personCard.Address.Line1 + (personCard.Address.Line2.length > 0 ? "," :"")}}</h1>
                            <h1 ng-if="personCard.Address.Line2 > 0" ng-bind="personCard.Address.Line2"></h1>
                        </td>
                        <td>
                            <label>Phone</label>
                            <h1 ng-bind="personCard.Phone"></h1>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <label>Regligion</label>
                            <h1>{{personCard.Religion}}</h1>
                        </td>
                        <td>
                            <label>Family?</label>
                            <h1>{{personCard.HasFamily ? (personCard.Gender == "m" ? "He" : "She") + " Got One!": "Free from Responsibilty"}}</h1>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2">
                            <label>Career Path</label>
                            <p>{{personCard.CareerPath.length > 0 ? personCard.CarrerPath : "Still hasn't decided"}}</p>
                        </td>
                    </tr>
                </table>
            </div>
            <div class="tab-content">
                <ul>
                    <li class="title">
                        <label>Skills</label>
                        <ul>
                            <li ng-repeat="skill in personCard.Skills">
                                <h1 ng-bind="skill.Name"></h1>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>

Rekrut/Views/Shared/Templates.cshtml
@{ 
    Layout = null;
}
<script type="text/ng-template" id="alertModal.html">
    <div class="modal-body">
        <h1>{{title}}</h1>
        <p>{{msg}}</p>
    </div>
    <div class="modal-footer">
        <button class="btn btn-warning" type="button" ng-click="close()">Ok</button>
    </div>
</script>

<script type="text/ng-template" id="personCard.html">
    <div class="with-tabs person-card animated" ng-class="closed ? 'slideOutUp' : 'slideInUp'">
        <div class="top">
            <button class="options"><i class="mdi mdi-dots-vertical"></i></button>
            <button class="close" ng-click="closeGlobalModal()"><i class="mdi mdi-close"></i></button>
            <div class="img-holder">
                <img ng-src="{{personCard.Img}}" alt="User Face" />
            </div>
            <div class="info">
                <h1>{{personCard.FirstName + " " + personCard.LastName}}: <b ng-bind="personCard.JobTitle"></b></h1>
                <h2 ng-bind="personCard.Department"></h2>
                <div class="detail-group clearfix">
                    <h3><b>Email:</b>{{personCard.Email}}</h3>
                    <h3><b>Ext.:</b>{{personCard.Extension}}</h3>
                </div>
            </div>
            <div class="tabs-nav">
                <button class="active">Personals</button>
                <button>Skills</button>
                <button>Pros & Cons</button>
                <button>Interests</button>
                <button>Credentials</button>
            </div>
        </div>
        <div class="bottom tab-content-holder">
            <div class="tab-content-holder-inner">
                <div class="tab-content active">
                    <table>
                        <tr>
                            <td>
                                <label>Address</label>
                                <h1>{{personCard.Address.Line1 + (personCard.Address.Line2.length > 0 ? "," :"")}}</h1>
                                <h1 ng-if="personCard.Address.Line2.length > 0" ng-bind="personCard.Address.Line2"></h1>
                            </td>
                            <td>
                                <label>Phone</label>
                                <h1 ng-bind="personCard.Phone"></h1>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <label>Religion</label>
                                <h1>{{personCard.Religion}}</h1>
                            </td>
                            <td>
                                <label>Family?</label>
                                <h1>{{personCard.HasFamily ? (personCard.Gender == "m" ? "He" : "She") + " Got One!": "Free from Responsibilty"}}</h1>
                            </td>
                        </tr>
                        <tr>
                            <td colspan="2">
                                <label>Career Path</label>
                                <p>{{personCard.CareerPath.length > 0 ? personCard.CareerPath : "Still hasn't decided"}}</p>
                            </td>
                        </tr>
                    </table>
                </div>
                <div class="tab-content">
                    <ul class="familiar">
                        <li class="title">
                            <h1 style="width:60%">Skill</h1>
                            <h1 style="width:17%; text-align:center;">Rating</h1>
                            <h1 style="width:20%; text-align:center;">Experience</h1>
                        </li>
                        <li ng-repeat="skill in personCard.Skills">
                            <h1 style="width:60%" ng-bind="skill.Name"></h1>
                            <h1 style="width:17%; text-align:center;"><b ng-bind="skill.Rating"></b>/10</h1>
                            <h1 style="width:20%; text-align:center;"><b ng-bind="skill.Experience"></b> years</h1>
                        </li>
                    </ul>
                </div>
                <div class="tab-content">
                    <ul>
                        <li class="title">
                            <label>Pros & Cons</label>
                            <ul>
                                <li ng-repeat="skill in personCard.skills">
                                    <h1 ng-bind="skill.name"></h1>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
                <div class="tab-content">
                    <ul>
                        <li class="title">
                            <label>Interests</label>
                            <ul>
                                <li ng-repeat="skill in personCard.skills">
                                    <h1 ng-bind="skill.name"></h1>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
                <div class="tab-content">
                    <ul>
                        <li class="title">
                            <label>Credentials</label>
                            <ul>
                                <li ng-repeat="skill in personCard.skills">
                                    <h1 ng-bind="skill.name"></h1>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</script>

Rekrut/Views/Shared/_AuthLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Rekrut | @ViewBag.Title</title>
    <link rel="icon" href="@Url.Content("~/Content/images/rekrut.ico")">
    <link href="@Url.Content("~/Content/css/global/reset.css")" rel="stylesheet" />
    <link href="@Url.Content("~/Content/css/global/animate.css")" rel="stylesheet" />
    <link href="@Url.Content("~/Content/css/auth.css")" rel="stylesheet" />
</head>
<body>
    @RenderBody()
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @RenderSection("Scripts", false)
</body>
</html>

Rekrut/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html ng-app="rekrut" ng-controller="mainCtrl">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title ng-bind="title"></title>
    <script src="/Scripts/ckeditor/ckeditor.js"></script>
    <link rel="icon" href="@Url.Content("~/Content/images/rekrut.ico")">
    @Styles.Render("~/Content/css/global")
    @Styles.Render("~/Content/css/global/bootstrap")
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body class="sml">
    <div id="head" class="clearfix">
        <div id="sidebarTop" class="clearfix">
            <a href="#"><b>R</b>ekrüt</a>
        </div>
        <div id="search">
            <input type="text" placeholder="Enter a keyword, skill, department or project" />
            <button class="search-settings"><i class="fa fa-sliders"></i></button>
            <button class="search-btn">Search</button>
        </div>
        <div id="user">
            <img ng-cloak ng-src="{{person.img}}" alt="user" />
            <div class="info">
                <h1 ng-cloak>{{person.firstName + " " + person.lastName}}</h1>
                <h2 ng-cloak>{{person.jobTitle}}</h2>
            </div>
        </div>
    </div>
    <div id="sidebar">
        <ul id="nav">
            <li><a href="#/" ng-class="{active : activePath == '/'}"><span>Dashboard</span><i class="nova-share-megaphone-2-1"></i></a></li>
            <li><a href="#/skilldirectory" ng-class="{active : activePath == '/skilldirectory'}"><span>Skill Directory</span><i class="nova-pencil-ruler-1"></i></a></li>
            <li>
                <a href="#/projects" ng-class="{active : activePath == '/projects'}">
                    <span>Projects</span><i class="nova-folder-check-1"></i>
                    <b ng-if="projects > 0" ng-cloak>{{projects}}</b>
                </a>
            </li>
            <li>
                <a href="#/applications" ng-class="{active : activePath == '/applications'}">
                    <span>Applications</span><i class="nova-devices"></i>
                    <b ng-if="applications > 0" ng-cloak>{{applications}}</b>
                </a>
            </li>
            <li>
                <a href="#/teams" ng-class="{active : activePath == '/teams'}">
                    <span>Applications</span><i class="nova-vector-triangle-1"></i>
                    <b ng-if="applications > 0" ng-cloak>{{applications}}</b>
                </a>
            </li>
            <li>
                <a href="#/taskbriefs" ng-class="{active : activePath == '/taskbriefs'}">
                    <span>Task Briefs</span><i class="nova-file-tasks-checklist"></i>
                    <b ng-if="tasks > 0" ng-cloak>{{tasks}}</b>
                </a>
            </li>
            <li><a href="#" ng-class="{active : activePath == '/settings'}"><span>Settings</span><i class="nova-settings-1"></i></a></li>
            <li>
                @using (Html.BeginForm("LogOff", "Auth", FormMethod.Post))
                {
                    @Html.AntiForgeryToken()
                    <button ng-click="logout($event)"><span>Logout</span><i class="mdi mdi-keyboard-backspace"></i></button>
                }
            </li>
        </ul>
    </div>

    @RenderBody()
    <div class="overlay animated fadeIn" ng-if="modal" ng-cloak></div>
    <div class="load-bar pageLoader" ng-if="pageLoading">
        <div class="bar"></div>
        <div class="bar"></div>
        <div class="bar"></div>
    </div>
    <div class="big-comparer-holder">
        <div class="comparer-switcher">
            <button><i class=""></i></button>
        </div>
        <div class="divider"></div>
        <div class="big-comparer left">
            <div class="details">
                <h1>Leithon English:<b>Programmer Analyst</b></h1>
                <div class="img-holder">
                    <img src="~/Content/images/guy-face.png" alt="face" />
                </div>
            </div>
            <div class="chart-holder">
                <canvas id="myChart1" width="400" height="400"></canvas>
            </div>
        </div>
        <div class="big-comparer right">
            <div class="chart-holder">
                <canvas id="myChart2" width="400" height="400"></canvas>
            </div>
        </div>
    </div>
    <div ng-include="url"></div>
    @Html.Partial("Templates")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/components")
    @Scripts.Render("~/bundles/angular")
    @Scripts.Render("~/bundles/angular-ui")
    @Scripts.Render("~/bundles/rekrut/angular")
    <script type="text/javascript">
        var data = {
            labels: ["Eating", "Drinking", "Sleeping", "Designing", "Coding", "Cycling", "Running"],
            datasets: [
                {
                    label: "My First dataset",
                    fillColor: "rgba(83, 181, 41, 0.20)",
                    strokeColor: "#53b529",
                    pointColor: "#3d9219",
                    pointStrokeColor: "#fff",
                    pointHighlightFill: "#fff",
                    pointHighlightStroke: "#53b529",
                    data: [65, 59, 90, 81, 56, 55, 40]
                }
            ]
        };
        var data1 = {
            labels: ["Eating", "Drinking", "Sleeping", "Designing", "Coding", "Cycling", "Running"],
            datasets: [
                {
                    label: "My Second dataset",
                    fillColor: "rgba(151,187,205,0.2)",
                    strokeColor: "rgba(151,187,205,1)",
                    pointColor: "rgba(151,187,205,1)",
                    pointStrokeColor: "#fff",
                    pointHighlightFill: "#fff",
                    pointHighlightStroke: "rgba(151,187,205,1)",
                    data: [28, 48, 40, 19, 96, 27, 100]
                }
            ]
        };
        var ctx = document.getElementById("myChart1").getContext("2d");
        var ctx1 = document.getElementById("myChart2").getContext("2d");
        var myRadarChart1 = new Chart(ctx1).Radar(data1);
        var myRadarChart = new Chart(ctx).Radar(data, {
            tooltipFillColor: "rgba(0,0,0,0.4)",
            tooltipFontFamily: "'Proxima Nova'",
            tooltipTitleFontStyle: "lighter",
            tooltipCornerRadius: 2,
        });
       
    </script>
</body>
</html>